version: '3.9'

services:
  app:
    image: dog-dog
    ports:
      - "8000:8000"
    working_dir: "/DOG-DOG/good_heartst_project"
    command: > 
      sh -c "python manage.py wait_for_db &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=DOG
      - DB_PASS=changename
    depends_on:
    - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"
volumes:
  dev-db-data:
