# Generated by Django 4.0.5 on 2022-06-24 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findhouse', '0002_animals_alter_helps_of_animals_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findhome',
            name='animals',
            field=models.ForeignKey(default='CAT', on_delete=django.db.models.deletion.PROTECT, to='findhouse.animals'),
        ),
    ]
