# Generated by Django 4.0.5 on 2022-06-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findhouse', '0003_alter_findhome_animals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findhome',
            name='animals',
        ),
        migrations.AddField(
            model_name='findhome',
            name='type_animal',
            field=models.CharField(choices=[('CAT', 'Котик'), ('DOG', 'Собачка')], default='CAT', max_length=3, verbose_name='Тип животного'),
        ),
        migrations.DeleteModel(
            name='Animals',
        ),
    ]
