# Generated by Django 4.0.5 on 2022-06-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Категория'),
        ),
    ]
